### PR TITLE
Features

### PR DESCRIPTION
**Pull request by Datagirlcmr**

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
#### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi Selma!  
#### Wow, your project looks :+1: 

But need some Required Changes
#### Page structure

##### Navigation bar

* [x] It contains Newsweek logo.
* [x] It contains current date.
* [ ] It contains Sign in and Subscribe links.
* [x] It contains main navigation links.
* [x] **It changes with RWD breakpoints.**

##### Footer
* [x] It contains Newsweek logo.
* [x] It contains social media icons.
* [ ] It contains main navigation links.
* [x] **It changes with RWD breakpoints.**
##### Please check responsiveness:
**** for example as you can see here ****



Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Comment by Anna-Myzukina** [comment]
#### Well all the part that are needed to declare this project as done is in here. 
#### Nice work image

### Project approved! image

#### You can merge it and don't forget to fill the project completion form.

It`s not optional, just my advice make a little changes in the top:
You added a link to Signup but now it looks very different with the original 

*** In your project ***
top1

*** In original ***
top

Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!



*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Review by Anna-Myzukina — APPROVED** [review]

**Comment by Datagirlcmr** [comment]
Thank You. I have fixed the subscribe link to look the same

**Pull request merged**
